### ISSUE TITLE
Building htop in a Docker container fails because of libncursesw6

### ISSUE THREAD

**Issue by stulluk** [Zackptg5/Misc-Binaries-For-Android-Build-Script#1]
I am trying to run build.sh in a docker container, but it always fails when it tries to build htop:

arm-linux-androideabi-clang -pedantic -Wall -Wextra -std=c99 -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/media/build-static/htop/arm/etc\" -I"./linux" -static -O2 -I/media/build-static/ncursesw/arm/include   -static -L/media/build-static/ncursesw/arm/lib -o htop   AvailableMetersPanel.o CategoriesPanel.o CheckItem.o ClockMeter.o ColorsPanel.o ColumnsPanel.o CPUMeter.o CRT.o MainPanel.o DisplayOptionsPanel.o FunctionBar.o Hashtable.o Header.o htop.o ListItem.o LoadAverageMeter.o MemoryMeter.o Meter.o MetersPanel.o Object.o Panel.o BatteryMeter.o Process.o ProcessList.o RichString.o ScreenManager.o Settings.o SignalsPanel.o StringUtils.o SwapMeter.o TasksMeter.o UptimeMeter.o TraceScreen.o UsersTable.o Vector.o AvailableColumnsPanel.o AffinityPanel.o HostnameMeter.o OpenFilesScreen.o Affinity.o IncSet.o Action.o EnvScreen.o InfoScreen.o XAlloc.o linux/Platform.o linux/IOPriorityPanel.o linux/LinuxProcess.o linux/LinuxProcessList.o linux/LinuxCRT.o linux/Battery.o linux/PressureStallMeter.o zfs/ZfsArcMeter.o zfs/ZfsCompressedArcMeter.o zfs/ZfsArcStats.o   -lncursesw6 -lm  
/media/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lncursesw6

Here is my dockerfile:

stulluk ~/Misc-Binaries-For-Android-Build-Script (st_add_docker_compile) $  cat Dockerfile 
FROM ubuntu:20.04

RUN apt -y update && apt -y upgrade

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

RUN apt -y install autoconf yodl git build-essential gcc-multilib wget unzip vim pkg-config

CMD "cd /media && ./build.sh"

I run this container as follows: docker run -it --privileged -v $(pwd):/media android-static-binaries /bin/bash -c "cd /media && ./build.sh"

I saw this one: https://github.com/spack/spack/issues/8534  but I don't know how to fix it.

Any ideas?

BTW: I am ready to create a pull request for my changes if you allow me.

**Comment by Zackptg5** [comment]
Try running manjaro or another arch based distro. I've only tested this on manjaro myself and I recall running into random issues with some binaries on ubuntu wsl
